name: Build

on: [push]

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: 'Deploy to Cloudflare'
      if: github.ref == 'refs/heads/master'
      uses: cloudflare/wrangler-action@1.1.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
  docker:
    if: github.ref == 'refs/heads/master'
    needs: [static]
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: docker/build-push-action@v5
        id: build
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}
          labels: ${{ steps.meta.outputs.labels }}
      # - uses: azure/setup-kubectl@v1
      #   with:
      #     version: 'v1.19.7'
      # - uses: azure/k8s-set-context@v1
      #   with:
      #     method: service-account
      #     k8s-url: ${{ secrets.K8S_URL }}
      #     k8s-secret: ${{ secrets.K8S_SECRET }}
      # - run: kubectl set image deployment/chickaree web=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/${GITHUB_REPOSITORY})


